sudo: required
dist: trusty

script:
  - bash -xve ./test/travis_ros_install.bash
  - source ~/catkin_ws/devel/setup.bash
  - bash -xve ./test/travis_package_make.bash
  - source ~/catkin_ws/devel/setup.bash
  - rostest pimouse_ros ~/home/travis/catkin_ws/src/pimouse_ros/test/test.launch
